services:
  postgres:
    image: postgres:15
    container_name: marketplace_postgres_db
    restart: always
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: